version: '3.4'

services:
  postgresql:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: changeme
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    restart: always
    environment:
        - discovery.type=single-node
        - cluster.name=docker-cluster
    ports:
        - 9200
        - 9300
    volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
  logstash:
    image: namdd72/logstash
    restart: always
    build: .
    depends_on:
        - postgresql
        - elasticsearch
    volumes:
        - ./logstash-pipeline/:/usr/share/logstash/pipeline/
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    restart: always
    ports:
        - 5601:5601
    depends_on:
        - elasticsearch

volumes:
  postgresql-data:
    external: true
  elasticsearch-data:
    external: true
